CREATE DATABASE IF NOT EXISTS EMPRESA
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE USER 'EMPRESA'@'%' IDENTIFIED BY 'EMPRESA';
--SET PASSWORD FOR 'EMPRESA'@'%' = PASSWORD('EMPRESA');

GRANT ALL ON EMPRESA.* TO 'EMPRESA'@'%';