CREATE TABLE EMPRESA (
EMPR_ID DECIMAL(15,0) NOT NULL,
EMPR_NAME VARCHAR(50) NOT NULL,
EMPR_NIT    VARCHAR(100) NOT NULL,
EMPR_CREDA  TIMESTAMP,
EMPR_ADRESS VARCHAR(60) NOT NULL
);

CREATE TABLE SEQUENCE_TABLE (

SEQ_NAME VARCHAR(100),
SEQ_COUNT DECIMAL(15,0)

);

ALTER TABLE EMPRESA ADD PRIMARY KEY(EMPR_ID);
ALTER TABLE SEQUENCE_TABLE ADD PRIMARY KEY(SEQ_NAME);

INSERT INTO SEQUENCE_TABLE (SEQ_NAME, SEQ_COUNT) VALUES ('EMPRESA_SEQ', 0);
